### ISSUE TITLE
support default values for XDG variables if they arnt set or empty

### ISSUE THREAD

**Issue by hornyjailfish** [jceb/dex#61]
if i run `dex -a -s $XDG_CONFIG_HOME/autostart` nothing happens because `XDG_CONFIG_HOME` not set by default 
But in [XDG specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) if some XDG enviroment variables not set it use default values
> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. **If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.** 

same for other env's

**Comment by wereii** [comment]
Just omit the `-s` then,  looking into the code there is a logic for defaulting.

That string is expanded by your shell so dex will never see the `$...`, it receives "/autostart" as a param to searchpaths and rolls 
with it, disabling the defaults. 

Also I would recommend setting the `XDG_*` env vars explicitly.

**Comment by timblaktu** [comment]
+1 to the idea of supporting standard XDG search path order instead of requiring user to specify -s or an abs path to a .desktop file. My use case:

I'm using Hyprland, and just like any card-carrying linux dork I want "all my things" to be runnable consistently from "all the places": 

1. my terminal
2. my WM/DE startup mechanism
3. my WM/DE launcher (dmenu, rofi, etc, anything that knows how to "run a .desktop file")

In most cases, 2. is a trivial variant of 1. as the WM/DE startup can usually be defined as command(s) to run. And re: 3. IME WM/DE launchers tend to know how to, and do, follow/handle XDG standards for search order of desktop entries.

So that leaves us with CLI tools like `dex` to handle 1-2.

I'm using dex to automate launching my ~/.local/share/applications/*.desktop when my Hyprland session starts, and am a bit dismayed that doing so requires explicit specification of the abspath to the file, which I'm doing like so:

```bash
# hyprland.conf

# running dex in login shell to ensure XDG_* vars are set/exported
exec-once = bash -lc "dex $XDG_DATA_HOME/applications/discord.desktop"
```

Here I'm simply proposing that `dex` support defaulting its `-s SEARCHPATHS, --search-paths SEARCHPATHS` arg to the XDG standard so that it will find the same file on my system using just the file name:

```bash
# hyprland.conf

# still have to run dex in login shell but I don't have to be explicit about _which_ to launch
exec-once = bash -lc "dex discord.desktop"
```

I believe most people just want tools like this to simplify their lives by following the standard search path order, which is defined in the aforelinked XDG Base Dir Spec:

>  $XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'.
> 
> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

and

>  The order of base directories denotes their importance; the first directory listed is the most important. When the same information is defined in multiple places the information defined relative to the more important base directory takes precedent. The base directory defined by $XDG_DATA_HOME is considered more important than any of the base directories defined by $XDG_DATA_DIRS. The base directory defined by $XDG_CONFIG_HOME is considered more important than any of the base directories defined by $XDG_CONFIG_DIRS.

and

> Referencing this specification
> 
> Other specifications may reference this specification by specifying the location of a data file as $XDG_DATA_DIRS/subdir/filename. This implies that:
> 
> * Such file should be installed to $datadir/subdir/filename with $datadir defaulting to /usr/share.
> * A user-specific version of the data file may be created in $XDG_DATA_HOME/subdir/filename, taking into account the default value for $XDG_DATA_HOME if $XDG_DATA_HOME is not set.
> * Lookups of the data file should search for ./subdir/filename relative to all base directories specified by $XDG_DATA_HOME and $XDG_DATA_DIRS . If an environment variable is either not set or empty, its default value as defined by this specification should be used instead. 

Without this behavior, I may just uninstall `dex` and replace my `exec-once` hyprland startup commands with the `Exec` stanza from the .desktop files...

...I think what I'm trying to do is so simple maybe I should just write it out in bash to further illustrate my needs, FWIW. Here goes...

```bash
#!/usr/bin/env bash
# Find and launch a .desktop file by name, using standard XDG search path order
#
# Per "Referencing this specification" in:
#   https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
set -euo pipefail
function main() {
  [[ $# -ne 1 ]] && echo "$(basename $0): ERROR ${FUNCNAME[1]}() requires exactly one arg \$1 = DESKTOP_FILENAME|DESKTOP_FILE_PATH\n" && exit 1
  local xdf="$1"
  local xdh="${XDG_DATA_HOME-"$HOME"/.local/share}"
  # if xdf is more than a basename, skip search and use directly
  if [ "$xdf" == "$(basename $xdf)" ]; then
    # search order is:
    #   1. $XDG_DATA_HOME/applications
    #   2. $XDG_DATA_DIRS[0]/applications
    #   3. $XDG_DATA_DIRS[1]/applications
    #   ...
    if [ -d "$xdh" ] && [ -f "$xdh"/applications/"$xdf" ]; then
      xdf="$xdh"/applications/"$xdf"
    else
      for d in $XDG_DATA_DIRS; do
        if [ -d "$d"/applications ] && [ -f "$d"/applications/"$xdf" ]; then
          xdf="$d"/applications/"$xdf"
          break
        fi
      done
    fi
  fi
  # xdf is now the path to the named desktop file
  # parse its Exec stanza and execute in a detached background subshell
  local cmdstr="$(sed -n 's/^Exec=\(.*\)$/\1/p' "$xdf")"
  local cmdary=( $cmdstr )
  "${cmdary[@]}" &
  local pid=$!
  printf "executing command '%s' in background process pid=%d\n" "${cmdary[*]}" "$pid"
}
main "$@"

```

**Comment by jceb** [comment]
Thanks for sharing your script. I think this issue needs to be solved outside dex. It comes with two modes of operation:
- autostart `dex -a` will search the XDG directories
- individual execution of desktop entry files

I guess one could argue that `dex -a` has gone too far by supporting search in autostart directories and the main use case should be simple execution. For example `dmenu` has a way cleaner interface by just supporting filtering and selection and leaving search and executing to `dmenu_run` and other programs. In this spirit, I don't want to complicate `dex` any further by adding support for other search paths than autostart. Please feel free to submit a PR for your `dex_run` script. I like the idea but it can't be part of the core executable.

**Comment by jceb** [comment]
I'll close this issue for now.
